# Generated by Django 3.0.8 on 2020-07-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Powers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('VOLADOR', 'Volador'), ('VELOCIDAD', 'Velocidad'), ('ATAQUE', 'Ataque')], max_length=20)),
                ('hero', models.ManyToManyField(to='principal.Hero')),
            ],
        ),
    ]
